name       : ktextwidgets
version    : 5.58.0
release    : 27
source     :
    - https://download.kde.org/stable/frameworks/5.58/ktextwidgets-5.58.0.tar.xz : 056601d7c1aa412a9628fae8eb6ca6cf51d0f0fab03345bb4be8e7072827fed7
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kiconthemes-devel
    - kservice-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
