name       : ktextwidgets
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/ktextwidgets-5.38.0.tar.xz : eef0847aa98489437784361a281a16cbd52b3ac8a1a83619c370078e96ea1288
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kiconthemes-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
