name       : ktextwidgets
version    : 5.77.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/ktextwidgets-5.77.0.tar.xz : 8371accab994192f1505b3bb4805badd751fabd4e8a8ca66cadbc039a253f0f2
homepage   : https://community.kde.org/Frameworks
license    :
    - LPGL-2.0-only
    - LPGL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kservice-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
