name       : ktextwidgets
version    : 5.92.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/ktextwidgets-5.92.0.tar.xz : fe867bf498a5170a9fba91dff652b68fa5cae2af8864dbe89a6e54638ff90b0c
homepage   : https://community.kde.org/Frameworks
license    :
    - LPGL-2.0-only
    - LPGL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
