name       : ktextwidgets
version    : 5.62.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/ktextwidgets-5.62.0.tar.xz : ec34931658cbe3a7ad7419a6e588cd9f9981e9b5ab2400e8b6f2b79b29f83774
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kiconthemes-devel
    - kservice-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
