name       : ktextwidgets
version    : 5.41.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/ktextwidgets-5.41.0.tar.xz : 7608a9f6b44acf2c9fbd483605dfd65004cce321ea0177909f8a6d69c126d654
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kiconthemes-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
