name       : ktextwidgets
version    : 5.51.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/ktextwidgets-5.51.0.tar.xz : 63e9f5ea730044d905857961e2857c78bbe9119f804768bb17fbbd9370f7b7a0
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kiconthemes-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
