name       : ktextwidgets
version    : 5.84.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/ktextwidgets-5.84.0.tar.xz : d4e1213e5475ec2f58f51206ef0473e324f834c1735fc81e8e49399d5d983819
homepage   : https://community.kde.org/Frameworks
license    :
    - LPGL-2.0-only
    - LPGL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
