name       : ktextwidgets
version    : 5.93.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/ktextwidgets-5.93.0.tar.xz : e27f588929db35f485ebbd6ddec45ec0c56f86844935013f8a39df8bdfb7c215
homepage   : https://community.kde.org/Frameworks
license    :
    - LPGL-2.0-only
    - LPGL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
