name       : ktextwidgets
version    : 5.40.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/ktextwidgets-5.40.0.tar.xz : d95412d49025c4c52dafb1056d1d153726126b0cad940841f85ff98dd4b4a236
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kiconthemes-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
