name       : ktextwidgets
version    : 5.107.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/ktextwidgets-5.107.0.tar.xz : 5e66b07f271a9aae03795ed1baef542460d77ede06987e312f56ebf2376da0fb
homepage   : https://community.kde.org/Frameworks
license    :
    - LPGL-2.0-only
    - LPGL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
