name       : ktextwidgets
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/ktextwidgets-5.25.0.tar.xz : 4b2d9b999ba9fbd7f79105d15f0c8bcc3f3f4982d0b71b1c06e4ade6d63eb614
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcompletion-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - sonnet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
